### ISSUE TITLE
Changes Required

### ISSUE THREAD

**Issue by danishxr** [MeenuMariaJose/File_Renamer#1]
# Details on the Changes required

1. Make the code such that you give the option to the user to rename a single file or all files in a directory
2. Use ArgeParse Library to get the command line arguments and provide options to the user.

---

## Some Examples

> Rename files in a directory by adding a keyword called `mouse` 

`file_renamer.py -d  /home/user/mydirectory -s "mouse"`

> Rename a single file 
`file_renamer.py -f "mydata.csv" -s "mouse"`

> Also, give proper information to the user the options in your tool when they type `--help`
`file_renamer.py --help`

**Comment by MeenuMariaJose** [comment]
i have added the specified changes
